### ISSUE TITLE
" rack-blogengine run ." encounter error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [tak1n/rack-blogengine#1]
hi.
i ran:
gem install rack-blogengine

then ran:
cd /usr/local/
rack-blogengine generate rack-blogengine-site
cd rack-blogengine-site

root@AR:/usr/local/rack-blogengine-site# rack-blogengine run .
	Set up ./assets/style/highlight.css
/usr/local/rvm/gems/ruby-2.3.0/gems/rack-blogengine-1.0.9/lib/rack/blogengine/command_line_interface.rb:87:in `generate_highlight_css': private method `open' called for Rack::File:Class (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/rack-blogengine-1.0.9/lib/rack/blogengine/command_line_interface.rb:32:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/rack-blogengine-1.0.9/bin/rack-blogengine:16:in `public_send'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/rack-blogengine-1.0.9/bin/rack-blogengine:16:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/rack-blogengine:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/rack-blogengine:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

root@AR:/usr/local/rack-blogengine-site#

**Comment by tak1n** [comment]
Released version `1.1.0` which includes this fix.

**Comment by luckypoem** [comment]
hi.

still not ok.

root@AR:/usr/local/rack-blogengine-site# gem install rack-blogengine --version=1.1.0
Fetching: rack-blogengine-1.1.0.gem (100%)
Please report any issues at: https://github.com/tak1n/rack-blogengine/issues/new
Successfully installed rack-blogengine-1.1.0
Parsing documentation for rack-blogengine-1.1.0
Installing ri documentation for rack-blogengine-1.1.0
Done installing documentation for rack-blogengine after 0 seconds
1 gem installed
root@AR:/usr/local/rack-blogengine-site# rack-blogengine run .
Could not find proper version of rack-blogengine (1.0.9) in any of the sources
Run `bundle install` to install missing gems.
root@AR:/usr/local/rack-blogengine-site#

**Comment by tak1n** [comment]
```
benny@benny-Lenovo-Y50-70:~/dev/ruby/rack-blogengine$ gem install rack-blogengine
Fetching: rack-blogengine-1.1.0.gem (100%)
Please report any issues at: https://github.com/tak1n/rack-blogengine/issues/new
Successfully installed rack-blogengine-1.1.0
Parsing documentation for rack-blogengine-1.1.0
Installing ri documentation for rack-blogengine-1.1.0
Done installing documentation for rack-blogengine after 0 seconds
1 gem installed
benny@benny-Lenovo-Y50-70:~/dev/ruby/rack-blogengine$ rack-blogengine run blog/
        Set up blog//assets/style/highlight.css
[2016-11-28 10:36:30] INFO  WEBrick 1.3.1
[2016-11-28 10:36:30] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
[2016-11-28 10:36:30] INFO  WEBrick::HTTPServer#start: pid=23287 port=3000
```

Can you execute `gem list rack-blogengine` and post me the result.

**Comment by luckypoem** [comment]
root@AR:/usr/local/rack-blogengine-site# gem list rack-blogengine

*** LOCAL GEMS ***

rack-blogengine (1.1.0)
root@AR:/usr/local/rack-blogengine-site#

**Comment by luckypoem** [comment]
root@AR:/usr/local/rack-blogengine-site# mkdir blog
root@AR:/usr/local/rack-blogengine-site# rack-blogengine run blog
/usr/local/rack-blogengine-site/lib/rack/blogengine/command_line_interface.rb:131:in `initialize': No such file or directory @ rb_sysopen - blog/config.yml (Errno::ENOENT)
	from /usr/local/rack-blogengine-site/lib/rack/blogengine/command_line_interface.rb:131:in `open'
	from /usr/local/rack-blogengine-site/lib/rack/blogengine/command_line_interface.rb:131:in `get_config'
	from /usr/local/rack-blogengine-site/lib/rack/blogengine/command_line_interface.rb:31:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/rack-blogengine-1.1.0/bin/rack-blogengine:16:in `public_send'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/rack-blogengine-1.1.0/bin/rack-blogengine:16:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/rack-blogengine:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/rack-blogengine:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
root@AR:/usr/local/rack-blogengine-site#

**Comment by luckypoem** [comment]
it's bcoz i use rvm?

**Comment by tak1n** [comment]
Could be idk.
Can you create a new rvm gemset and execute following steps:

```
gem install rack-blogengine
rack-blogengine generate blog
rack-blogengine run blog
```

**Comment by luckypoem** [comment]
hi.

now it's ok:

root@AR:/usr/local# rack-blogengine generate rack-blogengine-site
	Generating folder skeleton

	Setting up essential Files
	Set up rack-blogengine-site/operator/operator.rb
	Set up rack-blogengine-site/config.yml
	Set up rack-blogengine-site/index.content
	Set up rack-blogengine-site/assets/layout/layout.html
	Set up rack-blogengine-site/assets/style/style.css
	Set up rack-blogengine-site/assets/js/script.js
	Set up rack-blogengine-site/Gemfile

	Setup finished! Have Fun
	To test it type rack-blogengine run rack-blogengine-site
root@AR:/usr/local# ls rack-blogengine-site
assets	config.yml  Gemfile  index.content  operator
root@AR:/usr/local# rack-blogengine run rack-blogengine-site
	Set up rack-blogengine-site/assets/style/highlight.css
[2016-11-29 04:20:20] INFO  WEBrick 1.3.1
[2016-11-29 04:20:20] INFO  ruby 2.3.0 (2015-12-25) [i686-linux]
[2016-11-29 04:20:20] INFO  WEBrick::HTTPServer#start: pid=16114 port=3000

but when i visit http://my_vps_ip:3000 ,it shows nothing.why?

root@AR:/usr/local# ls rack-blogengine-site
assets	config.yml  Gemfile  index.content  operator
root@AR:/usr/local#

and no static website is generated.why?

**Comment by tak1n** [comment]
The Command `generate` is just to create a project skeleton for you. All other things you have todo urself.

Also I didn't finish this project where it will build html files out of your generated folder (which contains those .content files).
You always have to use `rack-blogengine run` for now.

If you want to use a more mature static site generator look at jekyll, middleman, nanoc etc (all 3 are also written in ruby)

For a non ruby alternative I can suggest: https://github.com/cobalt-org/cobalt.rs

This project was only for learning purposes.
